# Generated by Django 5.2.8 on 2026-03-01 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('profile_image', models.ImageField(upload_to='profiles/')),
                ('resume', models.FileField(upload_to='resumes/')),
                ('skills', models.TextField(help_text='Comma separated skills')),
                ('certificates', models.TextField(help_text='Certificates info')),
                ('github', models.URLField(blank=True)),
                ('linkedin', models.URLField(blank=True)),
            ],
        ),
    ]
